export const REQUEST_ANALYTICS_RESULTS = 'REQUEST_ANALYTICS_RESULTS';
export const RECEIVE_ANALYTICS_RESULTS = 'RECEIVE_ANALYTICS_RESULTS';
export const FAILURE_ANALYTICS_RESULTS = 'FAILURE_ANALYTICS_RESULTS';
