apiVersion: v1
kind: Pod
metadata:
  name: node-TEST_NAME
  labels:
    app: node-TEST_NAME
spec:
  volumes:                          
    - name: dshm
      emptyDir:
        medium: Memory
  containers:
    - name: node-TEST_NAME
      image: 626313752456.dkr.ecr.eu-west-1.amazonaws.com/analytical-node
      imagePullPolicy: Always
      args:
      command: [ '/bin/bash', '-c' ]
      args: [ 'echo "OPTIONAL_IP OPTIONAL_DNS" >> /etc/hosts; node index.js CSV_FILES AUTHENTICATION_PROFILE_ID' ]
      env:
        - name: http_proxy
          value: 'http://172.31.43.13:3128'
        - name: https_proxy
          value: 'http://172.31.43.13:3128'
      resources:
        requests:
          cpu: 3000m
          memory: 4000Mi
      ports:
        - containerPort: 4444
          protocol: TCP
      volumeMounts:                 
        - mountPath: /dev/shm
          name: dshm
  imagePullSecrets:
    - name: regsecret
  restartPolicy: Never
