export const REQUEST_ERRORS_CSV = 'REQUEST_ERRORS_CSV';
export const RECEIVE_ERRORS_CSV = 'RECEIVE_ERRORS_CSV';
export const FAILURE_ERRORS_CSV = 'FAILURE_ERRORS_CSV';
export const REQUEST_RESPONSES_CSV = 'REQUEST_RESPONSES_CSV';
export const RECEIVE_RESPONSES_CSV = 'RECEIVE_RESPONSES_CSV';
export const FAILURE_RESPONSES_CSV = 'FAILURE_RESPONSES_CSV';
