apiVersion: v1
kind: Pod
metadata:
  name: analytics-rexona
  labels:
    app: analytics-rexona
spec:
  volumes:                          
    - name: dshm
      emptyDir:
        medium: Memory
  containers:
    - name: analytics-rexona
      image: arorasmail/analytics-automation:latest
      imagePullPolicy: Always
      args:
      command: [ '/bin/bash', '-c' ]
      args: [ 'echo "OPTIONAL_IP OPTIONAL_DNS" >> /etc/hosts; node index.js https://www.rexona.com/sitemap.xml' ]
      env:
      resources:
        requests:
          cpu: 3000m
          memory: 4000Mi
      ports:
        - containerPort: 4444
          protocol: TCP
      volumeMounts:                 
        - mountPath: /dev/shm
          name: dshm
  imagePullSecrets:
    - name: regalanytics
  restartPolicy: Never